const ISO=/^[A-Z]{3}$/;
export function money(minor,currency="EUR"){if(!Number.isSafeInteger(minor)||minor<0)throw new RangeError("money minor must be a non-negative safe integer");if(!ISO.test(currency))throw new RangeError("currency must be ISO-4217 alpha-3");return Object.freeze({minor,currency})}
const ML_PER={ml:1,cl:10,oz:30};
export function normalizedQuantity(amount,unit){if(!Number.isFinite(amount)||amount<=0)throw new RangeError("quantity must be > 0");unit=String(unit).trim().toLowerCase();if(!(unit in ML_PER))throw new RangeError("unsupported unit");return Object.freeze({amount,unit,ml:amount*ML_PER[unit]})}
export function priceObservation({ingredientId,supplier,invoiceId,observedAt,paidPrice,purchasedQuantity}){if(!ingredientId||!supplier||!invoiceId)throw new RangeError("identity fields required");const q=purchasedQuantity;if(!q||q.ml<=0)throw new RangeError("purchased quantity must be > 0");return Object.freeze({ingredientId,supplier,invoiceId,observedAt:new Date(observedAt).toISOString(),paidPrice,purchasedQuantity:q,unitCostMinorPerMl:paidPrice.minor/q.ml})}
export function comparePrices(previous,current){if(previous.paidPrice.currency!==current.paidPrice.currency)throw new RangeError("currency mismatch");const absoluteDelta=current.unitCostMinorPerMl-previous.unitCostMinorPerMl;const percentageDelta=previous.unitCostMinorPerMl===0?(absoluteDelta===0?0:null):Math.round(((absoluteDelta/previous.unitCostMinorPerMl)*100)*1e9)/1e9;return {absoluteDeltaMinorPerMl:absoluteDelta,percentageDelta}}
export function recipeCost(observations,consumptions){let total=0,currency=null;for(const c of consumptions){const o=observations.get(c.ingredientId);if(!o)throw new RangeError("missing ingredient price");if(currency&&currency!==o.paidPrice.currency)throw new RangeError("currency mismatch");currency=o.paidPrice.currency;total+=o.unitCostMinorPerMl*c.quantity.ml}return {minor:Math.round(total),currency:currency??"EUR"}}
export function recipeCostImpact(prev,curr,consumptions){const a=recipeCost(prev,consumptions),b=recipeCost(curr,consumptions);if(a.currency!==b.currency)throw new RangeError("currency mismatch");return {previous:a,current:b,deltaMinor:b.minor-a.minor}}
export function menuMarginImpact({sellingPrice,previousRecipeCost,currentRecipeCost}){if(sellingPrice.currency!==previousRecipeCost.currency||sellingPrice.currency!==currentRecipeCost.currency)throw new RangeError("currency mismatch");const previousMarginMinor=sellingPrice.minor-previousRecipeCost.minor,currentMarginMinor=sellingPrice.minor-currentRecipeCost.minor;return {previousMarginMinor,currentMarginMinor,marginDeltaMinor:currentMarginMinor-previousMarginMinor}}
