import test from"node:test";import assert from"node:assert/strict";import{money,normalizedQuantity,priceObservation,comparePrices,recipeCostImpact,menuMarginImpact}from"./impact.mjs";
const obs=(id,minor,amount=1000,unit="ml",currency="EUR",invoiceId="i1")=>priceObservation({ingredientId:id,supplier:"s",invoiceId,observedAt:"2026-09-24T00:00:00Z",paidPrice:money(minor,currency),purchasedQuantity:normalizedQuantity(amount,unit)});
test("money uses integer minor units",()=>{assert.deepEqual(money(1234),{minor:1234,currency:"EUR"});assert.throws(()=>money(1.2));assert.throws(()=>money(-1))});
test("quantity normalizes ml cl oz",()=>{assert.equal(normalizedQuantity(100,"cl").ml,1000);assert.equal(normalizedQuantity(1,"oz").ml,30);assert.throws(()=>normalizedQuantity(0,"ml"));assert.throws(()=>normalizedQuantity(1,"l"))});
test("unit cost and price increase/decrease",()=>{const a=obs("gin",1000),b=obs("gin",1200,1000,"ml","EUR","i2"),c=obs("gin",800,1000,"ml","EUR","i3");assert.equal(a.unitCostMinorPerMl,1);assert.equal(comparePrices(a,b).percentageDelta,20);assert.equal(comparePrices(a,c).percentageDelta,-20)});
test("currency mismatch fails closed",()=>assert.throws(()=>comparePrices(obs("x",100),obs("x",100,1000,"ml","USD","i2"))));
test("zero baseline is explicit not division by zero",()=>{const a=obs("x",0),b=obs("x",100);assert.equal(comparePrices(a,b).percentageDelta,null);assert.equal(comparePrices(a,a).percentageDelta,0)});
test("1-N observations remain independently attributable",()=>{const xs=[obs("x",100,1000,"ml","EUR","i1"),obs("x",110,1000,"ml","EUR","i2")];assert.deepEqual(xs.map(x=>x.invoiceId),["i1","i2"])});
test("recipe cost propagates ingredient price delta",()=>{const q=[{ingredientId:"gin",quantity:normalizedQuantity(50,"ml")},{ingredientId:"vermouth",quantity:normalizedQuantity(25,"ml")}];const p=new Map([["gin",obs("gin",1000)],["vermouth",obs("vermouth",800)]]);const c=new Map([["gin",obs("gin",1200)],["vermouth",obs("vermouth",800)]]);const r=recipeCostImpact(p,c,q);assert.equal(r.previous.minor,70);assert.equal(r.current.minor,80);assert.equal(r.deltaMinor,10)});
test("menu margin propagates recipe cost delta",()=>{const x=menuMarginImpact({sellingPrice:money(1200),previousRecipeCost:money(300),currentRecipeCost:money(350)});assert.deepEqual(x,{previousMarginMinor:900,currentMarginMinor:850,marginDeltaMinor:-50})});

test("additional adversarial money and quantity guards",()=>{assert.throws(()=>money(Number.MAX_SAFE_INTEGER+1));assert.throws(()=>money(1,"eur"));assert.throws(()=>normalizedQuantity(-1,"ml"));assert.throws(()=>normalizedQuantity(Number.NaN,"ml"))});
test("missing ingredient price fails closed",()=>{const q=[{ingredientId:"missing",quantity:normalizedQuantity(10,"ml")}];assert.throws(()=>recipeCostImpact(new Map(),new Map(),q))});
test("cross-currency recipe fails closed",()=>{const q=[{ingredientId:"a",quantity:normalizedQuantity(10,"ml")},{ingredientId:"b",quantity:normalizedQuantity(10,"ml")}];const p=new Map([["a",obs("a",100,1000,"ml","EUR")],["b",obs("b",100,1000,"ml","USD")]]);assert.throws(()=>recipeCostImpact(p,p,q))});
test("negative margin and delta sign are preserved",()=>{const x=menuMarginImpact({sellingPrice:money(300),previousRecipeCost:money(250),currentRecipeCost:money(350)});assert.deepEqual(x,{previousMarginMinor:50,currentMarginMinor:-50,marginDeltaMinor:-100})});
test("menu currency mismatch fails closed",()=>assert.throws(()=>menuMarginImpact({sellingPrice:money(300,"EUR"),previousRecipeCost:money(100,"USD"),currentRecipeCost:money(100,"USD")})));
